networks:
  spring-mysql:
    driver: bridge


services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    networks:
      - spring-mysql

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - spring-mysql  # ← add this
    depends_on:
      - app
    command: npx live-server --port=8080 --host=0.0.0.0
